# Generated by Django 6.0.2 on 2026-02-22 05:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField(help_text='Area in acres')),
                ('number_of_trees', models.PositiveIntegerField(default=0, help_text='Number of rubber trees')),
                ('location', models.TextField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='PostGIS polygon boundary', null=True, srid=4326)),
                ('area_sq_meters', models.FloatField(blank=True, help_text='Computed area in square meters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager who owns this block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/managers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TapperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('wage', models.DecimalField(decimal_places=2, help_text='Daily wage in Rupees', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/tappers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Manager who created this tapper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tappers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tapper_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TapperAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.block')),
                ('tapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.tapperprofile')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='LatexCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(auto_now_add=True)),
                ('quantity', models.FloatField(help_text='Quantity in liters')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS location at time of collection', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.block')),
                ('tapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.tapperprofile')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'unique_together': {('tapper', 'date')},
            },
        ),
    ]
