# Generated by Django 6.0.2 on 2026-02-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='area_hectares',
            field=models.FloatField(blank=True, help_text='PostGIS calculated area in hectares', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='area_sq_m',
            field=models.FloatField(blank=True, help_text='PostGIS calculated area in square meters', null=True),
        ),
    ]
