# Generated by Django 6.0.2 on 2026-02-22 06:03

import django.contrib.gis.db.models.fields
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_block_area_hectares_block_area_sq_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='GPS location at time of check-in', srid=4326)),
                ('accuracy_m', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('boundary', '&&')], name='exclude_overlapping_blocks'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.block'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('tapper', 'date')},
        ),
    ]
