# Generated by Django 6.0.2 on 2026-02-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_block_exclude_overlapping_blocks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in_time',
            new_name='created_at',
        ),
    ]
