# Generated by Django 6.0.2 on 2026-02-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_incidentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='minimum_daily_yield',
            field=models.FloatField(default=30),
        ),
        migrations.CreateModel(
            name='WageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('attendance_days', models.IntegerField()),
                ('total_latex_kg', models.FloatField()),
                ('daily_rate', models.FloatField(default=500)),
                ('per_kg_rate', models.FloatField(default=12)),
                ('base_wage', models.FloatField()),
                ('production_wage', models.FloatField()),
                ('total_wage', models.FloatField()),
                ('expected_yield', models.FloatField()),
                ('performance_percentage', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tapper', 'month')},
            },
        ),
    ]
